/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedTicketsRouteImport } from './routes/_authenticated/tickets'
import { Route as AuthenticatedQueuesRouteImport } from './routes/_authenticated/queues'
import { Route as AuthenticatedKnowledgeBaseRouteImport } from './routes/_authenticated/knowledge-base'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as AuthenticatedBroadcastRouteImport } from './routes/_authenticated/broadcast'
import { Route as AuthenticatedTicketTicketNumberRouteImport } from './routes/_authenticated/ticket.$ticketNumber'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTicketsRoute = AuthenticatedTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedQueuesRoute = AuthenticatedQueuesRouteImport.update({
  id: '/queues',
  path: '/queues',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedKnowledgeBaseRoute =
  AuthenticatedKnowledgeBaseRouteImport.update({
    id: '/knowledge-base',
    path: '/knowledge-base',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBroadcastRoute = AuthenticatedBroadcastRouteImport.update({
  id: '/broadcast',
  path: '/broadcast',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTicketTicketNumberRoute =
  AuthenticatedTicketTicketNumberRouteImport.update({
    id: '/ticket/$ticketNumber',
    path: '/ticket/$ticketNumber',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/broadcast': typeof AuthenticatedBroadcastRoute
  '/chat': typeof AuthenticatedChatRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/knowledge-base': typeof AuthenticatedKnowledgeBaseRoute
  '/queues': typeof AuthenticatedQueuesRoute
  '/tickets': typeof AuthenticatedTicketsRoute
  '/users': typeof AuthenticatedUsersRoute
  '/ticket/$ticketNumber': typeof AuthenticatedTicketTicketNumberRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/broadcast': typeof AuthenticatedBroadcastRoute
  '/chat': typeof AuthenticatedChatRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/knowledge-base': typeof AuthenticatedKnowledgeBaseRoute
  '/queues': typeof AuthenticatedQueuesRoute
  '/tickets': typeof AuthenticatedTicketsRoute
  '/users': typeof AuthenticatedUsersRoute
  '/ticket/$ticketNumber': typeof AuthenticatedTicketTicketNumberRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/broadcast': typeof AuthenticatedBroadcastRoute
  '/_authenticated/chat': typeof AuthenticatedChatRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/knowledge-base': typeof AuthenticatedKnowledgeBaseRoute
  '/_authenticated/queues': typeof AuthenticatedQueuesRoute
  '/_authenticated/tickets': typeof AuthenticatedTicketsRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/ticket/$ticketNumber': typeof AuthenticatedTicketTicketNumberRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/broadcast'
    | '/chat'
    | '/dashboard'
    | '/knowledge-base'
    | '/queues'
    | '/tickets'
    | '/users'
    | '/ticket/$ticketNumber'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/broadcast'
    | '/chat'
    | '/dashboard'
    | '/knowledge-base'
    | '/queues'
    | '/tickets'
    | '/users'
    | '/ticket/$ticketNumber'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/broadcast'
    | '/_authenticated/chat'
    | '/_authenticated/dashboard'
    | '/_authenticated/knowledge-base'
    | '/_authenticated/queues'
    | '/_authenticated/tickets'
    | '/_authenticated/users'
    | '/_authenticated/ticket/$ticketNumber'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tickets': {
      id: '/_authenticated/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof AuthenticatedTicketsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/queues': {
      id: '/_authenticated/queues'
      path: '/queues'
      fullPath: '/queues'
      preLoaderRoute: typeof AuthenticatedQueuesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/knowledge-base': {
      id: '/_authenticated/knowledge-base'
      path: '/knowledge-base'
      fullPath: '/knowledge-base'
      preLoaderRoute: typeof AuthenticatedKnowledgeBaseRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/broadcast': {
      id: '/_authenticated/broadcast'
      path: '/broadcast'
      fullPath: '/broadcast'
      preLoaderRoute: typeof AuthenticatedBroadcastRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ticket/$ticketNumber': {
      id: '/_authenticated/ticket/$ticketNumber'
      path: '/ticket/$ticketNumber'
      fullPath: '/ticket/$ticketNumber'
      preLoaderRoute: typeof AuthenticatedTicketTicketNumberRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedBroadcastRoute: typeof AuthenticatedBroadcastRoute
  AuthenticatedChatRoute: typeof AuthenticatedChatRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedKnowledgeBaseRoute: typeof AuthenticatedKnowledgeBaseRoute
  AuthenticatedQueuesRoute: typeof AuthenticatedQueuesRoute
  AuthenticatedTicketsRoute: typeof AuthenticatedTicketsRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedTicketTicketNumberRoute: typeof AuthenticatedTicketTicketNumberRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedBroadcastRoute: AuthenticatedBroadcastRoute,
  AuthenticatedChatRoute: AuthenticatedChatRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedKnowledgeBaseRoute: AuthenticatedKnowledgeBaseRoute,
  AuthenticatedQueuesRoute: AuthenticatedQueuesRoute,
  AuthenticatedTicketsRoute: AuthenticatedTicketsRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedTicketTicketNumberRoute: AuthenticatedTicketTicketNumberRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
